name: BM_cytology
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.8.0.121=hcdd5f01_5
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=ha770c72_1
  - gdk-pixbuf=2.44.5=h2b0a6b4_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.25=h17f619e_0
  - libdicom=1.2.0=hb03c661_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libglib=2.86.3=h8b17d9a_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.0=h5eee18b_0
  - libpng=1.6.54=h421ea60_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openjpeg=2.5.4=h55fea9a_0
  - openslide=4.0.0=h582fa3c_6
  - openssl=3.6.1=h35e630c_1
  - pcre2=10.46=h1321c63_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h543edf9_3_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.51.1=hbc0de68_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.4.0
      - astunparse==1.6.3
      - certifi==2025.4.26
      - cffi==2.0.0
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cryptography==46.0.4
      - cycler==0.12.1
      - filelock==3.18.0
      - flatbuffers==25.12.19
      - fonttools==4.58.2
      - fsspec==2025.5.1
      - gast==0.4.0
      - google-auth==2.48.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - hf-xet==1.1.3
      - huggingface-hub==0.33.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.10.1
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - openslide-python==1.4.2
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - protobuf==3.19.6
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - git+https://github.com/hirsch-lab/roc-utils.git
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - tensorflow==2.10.0
      - tensorflow-addons==0.23.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - timm==0.9.8
      - topk==1.0
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typeguard==2.13.3
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.5
      - wrapt==2.1.0
prefix: /home/user/anaconda3/envs/BM_cytology
